services:
  app:
    build: .
    container_name: taxi_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taxibooking
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: always

  mysql:
    image: mysql:8.0
    container_name: taxi_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: taxibooking
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - taxi_db:/var/lib/mysql
    restart: always

volumes:
  taxi_db:
